# Default values for eveseat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mariadb:
    replication:
        enabled: false
    name: seat
    user: seat
    password:

redis:
    cluster:
        enabled: false
    password:

web:
    replicaCount: 1

    image:
        repository: eveseat/eveseat-nginx
        tag: latest
        pullPolicy: IfNotPresent

    service:
        type: ClusterIP
        port: 80

    resources: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}

app:
    replicaCount: 1

    image:
        repository: eveseat/eveseat-app
        tag: latest
        pullPolicy: IfNotPresent

    resources: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}

worker:
    replicaCount: 1

    image:
        repository: eveseat/eveseat-worker
        tag: latest
        pullPolicy: IfNotPresent

    resources: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}

cron:
    replicaCount: 1

    image:
        repository: eveseat/eveseat-cron
        tag: latest
        pullPolicy: IfNotPresent

    resources: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

global:
  app:
    url:
    debug: false
    key:
    env: local

  eve:
    clientId:
    clientSecret:

  mail:
    driver: smtp
    host:
    port: 587
    username:
    password:
    encryption: ntls
    fromAddress:
    fromName:

  seat:
    plugins:

